export const STUDENT_DATA = "STUDENT_DATA";
export const STUDENT_DATA_SET = "STUDENT_DATA_SET";
export const STUDENT_REGISTRATION = "STUDENT_REGISTRATION";
export const STUDENT_DELETE = "STUDENT_DELETE";
